<?php


class AWSMessages
{
    private $client;
    private $sqsUrl;

    public function __construct($client, $sqsUrl)
    {
        $this->client = $client;
        $this->sqsUrl = $sqsUrl;
    }

    function receiveMessage()
    {
        try {
            $result = $this->client->receiveMessage(array(
                'AttributeNames' => ['SentTimestamp'],
                'MaxNumberOfMessages' => 1,
                'MessageAttributeNames' => ['All'],
                'QueueUrl' => $this->sqsUrl,
                'WaitTimeSeconds' => 0,
            ));
            $message = $result['Messages'];
            if (!empty($result->get('Messages'))) {

                $result = $this->client->deleteMessage([
                    'QueueUrl' => $this->sqsUrl,
                    'ReceiptHandle' => $result->get('Messages')[0]['ReceiptHandle']
                ]);
            } else {
                return "No messages in queue. \n";
            }
        } catch (AwsException $e) {
            return $e->getMessage();
        }
        return $message;

    }

    function sendMessage($sended)
    {
        $result = false;
        if ($sended) {
            foreach ($sended as $one) {
                $params = [
                    'DelaySeconds' => 10,
                    'MessageAttributes' => [
                        "Title" => [
                            'DataType' => "String",
                            'StringValue' => "Autogenerated message"
                        ],
                        "Author" => [
                            'DataType' => "String",
                            'StringValue' => "Pushed files"
                        ],
                    ],
                    'MessageBody' => $one['ObjectURL'],
                    'QueueUrl' => $this->sqsUrl
                ];
                try {
                    $result = $this->client->sendMessage($params);
                    $result = 'Message send';
                } catch (AwsException $e) {
                    $result = 'Send message error : ' . $e->getMessage();
                }
            }


        } else {
            return $result;
        }
    }


}